### ISSUE TITLE
Fix uninstallation of Java in case more versions are present

### ISSUE THREAD

**Issue by radeksimko** [caskroom/homebrew-versions#287]
Simulate the situation:
```
brew cask install java6 java7 java
brew cask uninstall java7
```

```
==> Running uninstall process for java7; your password may be necessary
==> Removing files from pkgutil Bill-of-Materials
Error: undefined method `each' for "/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK":String
Please report this bug:
    https://github.com/caskroom/homebrew-cask/issues
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/artifact/pkg.rb:157:in `manually_uninstall'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/artifact/pkg.rb:66:in `block in uninstall'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each_key'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/set.rb:232:in `each'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/artifact/pkg.rb:66:in `uninstall'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/installer.rb:127:in `block in uninstall_artifacts'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/installer.rb:125:in `each'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/installer.rb:125:in `uninstall_artifacts'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/installer.rb:117:in `uninstall'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/uninstall.rb:9:in `block in run'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/uninstall.rb:5:in `each'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli/uninstall.rb:5:in `run'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli.rb:57:in `run_command'
/usr/local/Cellar/brew-cask/0.35.0/rubylib/cask/cli.rb:72:in `process'
/usr/local/bin/brew-cask.rb:6:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Library/brew.rb:65:in `require?'
/usr/local/Library/brew.rb:112:in `<main>'
```

**Comment by fanquake** [comment]
@bdhess If you wouldn't mind, can you offer any insight here? Is this still an issue/fixable?

**Comment by bdhess** [comment]
With the changes made for caskroom/homebrew-cask#13941, the Java casks no longer create symlinks under /System OS >= Yosemite, and this issue no longer presents.  Not sure if a fix for <= Mavericks is worthwhile.
