### ISSUE TITLE
java7 download fails

### ISSUE THREAD

**Issue by willglynn** [caskroom/homebrew-versions#3902]
#### Description of issue

The JDK7 download is now 404:

```
$ brew tap caskroom/versions
==> Tapping caskroom/versions
…
Tapped 0 formulae (197 files, 258.5KB)
$ brew cask install java7
…
==> Downloading http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg
######################################################################## 100.0%
curl: (22) The requested URL returned error: 404 Not Found
```

A [StackOverflow question](https://stackoverflow.com/questions/44131983/wget-curl-download-of-oracle-java-7-sdk-from-the-oracle-archive-page) contains some analysis which seems applicable here.

#### Output of your command with `--verbose --debug`

```
$ brew cask install java7 --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
This Cask makes minor modifications to the JRE to prevent any packaged
application issues.

If your Java application still asks for JRE installation, you might need to
reboot or logout/login.

The JRE packaging bug is discussed here:

    https://bugs.eclipse.org/bugs/show_bug.cgi?id=411361

Installing this Cask means you have AGREED to the Oracle Binary Code License
Agreement for Java SE at

    http://www.oracle.com/technetwork/java/javase/terms/license/index.html

==> Hbc::Installer#fetch
==> Downloading
==> Downloading http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg
==> Calling curl with args ["http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg", "-C", "0", "-o", "#<Pathname:/Users/willglynn/Library/Caches/Homebrew/Cask/java7--1.7.0_80.dmg.incomplete>", "-b", "oraclelicense=accept-securebackup-cookie"]
/usr/bin/curl --remote-time --location --user-agent Homebrew/1.2.1-92-ge931fee732 (Macintosh; Intel Mac OS X 10.12.4) curl/7.51.0 --fail http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg -C 0 -o /Users/willglynn/Library/Caches/Homebrew/Cask/java7--1.7.0_80.dmg.incomplete -b oraclelicense=accept-securebackup-cookie
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   457  100   457    0     0    826      0 --:--:-- --:--:-- --:--:--   826
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'java7' with message: Download failed: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-macosx-x64.dmg
The incomplete download is cached at /Users/willglynn/Library/Caches/Homebrew/Cask/java7--1.7.0_80.dmg.incomplete
Error: nothing to install/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:17:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:34:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:149:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:154:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:140:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.2.1-92-ge931fee732
caskroom/homebrew-cask (git revision 65c352; last commit 2017-05-25)
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (2 files, 226.6MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3617 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (161 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/Library/Ruby/Site/2.0.0
/Library/Ruby/Site/2.0.0/x86_64-darwin16
/Library/Ruby/Site/2.0.0/universal-darwin16
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby/2.0.0/universal-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/x86_64-darwin16
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/universal-darwin16
==> Environment Variables
LANG="en_US.UTF-8"
PATH="…"
SHELL="/bin/bash"
```

**Comment by miccal** [comment]
<img width="545" alt="screen shot 2017-05-26 at 07 50 54" src="https://cloud.githubusercontent.com/assets/6127163/26475121/1c732024-41e8-11e7-990f-e161af3140c6.png">

**Comment by commitay** [comment]
> Seems to require a login now.

Nothing we can really do about this unless we switch to an unofficial mirror.

https://github.com/caskroom/homebrew-versions/pull/3914
