### ISSUE TITLE
caskroom/versions/firefox-esr can not be installed if caskroom/cask/firefox is installed

### ISSUE THREAD

**Issue by scottrigby** [caskroom/homebrew-versions#5035]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

[caskroom/versions/firefox-esr](https://github.com/caskroom/homebrew-versions/blob/master/Casks/firefox-esr.rb) can not be installed if [caskroom/cask/firefox](https://github.com/caskroom/homebrew-cask/blob/master/Casks/firefox.rb) is already present.

#### Output of your command with `--verbose --debug`

```sh
$ brew cask install firefox-esr --verbose --debug
==> Hbc::Installer#install
==> Printing caveats
==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading https://download-installer.cdn.mozilla.net/pub/firefox/releases/52.5.3esr/mac/en-US/Firefox%2052.5.3esr.dmg
Already downloaded: /Users/scottrigby/Library/Caches/Homebrew/Cask/firefox-esr--52.5.3.dmg
==> Downloaded to -> /Users/scottrigby/Library/Caches/Homebrew/Cask/firefox-esr--52.5.3.dmg
==> Verifying download
==> Determining which verifications to run for Cask firefox-esr
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask firefox-esr
==> SHA256 checksums match
==> Installing Cask firefox-esr
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/scottrigby/Library/Caches/Homebrew/Cask/firefox-esr--52.5.3.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/scottrigby/Library/Caches/Homebrew/Cask/firefox-esr--52.5.3.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/d20171229-33528-fld8ku", "/Users/scottrigby/Library/Caches/Homebrew/Cask/firefox-esr--52.5.3.dmg"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/20171229-33528-1wnodtj.list", "--", "/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/20171229-33528-wjs2x9.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/20171229-33528-wjs2x9.bom", "--", "/private/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/d20171229-33528-fld8ku/dmg.JOxhfX", "/usr/local/Caskroom/firefox-esr/52.5.3"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/rr/_0y6r0p53_j8qpsg39plhg9c0000gn/T/d20171229-33528-fld8ku/dmg.JOxhfX"]
==> Creating metadata directory /usr/local/Caskroom/firefox-esr/.metadata/52.5.3/20171229215000.957.
==> Creating metadata subdirectory /usr/local/Caskroom/firefox-esr/.metadata/52.5.3/20171229215000.957/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x0000010480b060>
==> Installing artifact of class Hbc::Artifact::App
==> Purging files for version 52.5.3 of Cask firefox-esr
Error: It seems there is already an App at '/Applications/Firefox.app'.
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:31:in `move'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/moved.rb:11:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
$ brew cask doctor
==> Homebrew-Cask Version
Homebrew-Cask 1.4.1-28-g7f54c83
caskroom/homebrew-cask (git revision d563; last commit 2017-12-29)
==> macOS
10.13.2
==> Java
1.8.0_112
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (6 files, 670.8MB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3879 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (176 casks)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/bash"
```

**Comment by commitay** [comment]
https://github.com/caskroom/homebrew-cask/pull/42383
https://github.com/caskroom/homebrew-versions/pull/5036

**Comment by jcrben** [comment]
Is the idea that we can't install beta or canary versions side by side with stable versions? Why not?
