### ISSUE TITLE
adobe-cs6-master-collection: cannot install with en_US language

### ISSUE THREAD

**Issue by teslamint** [caskroom/homebrew-versions#5233]
#### General troubleshooting steps

- [x] I have retried my command with `--force` and the issue is still present.
- [x] I have checked the instructions for [reporting bugs](https://github.com/caskroom/homebrew-cask#reporting-bugs) (or [making requests](https://github.com/caskroom/homebrew-cask#requests)) before opening the issue.
  - [x] None of the templates was appropriate for my issue, or I’m not sure.
- [x] I ran `brew update-reset && brew update` and retried my command.
- [x] I ran `brew doctor`, fixed as many issues as possible and retried my command.
- [x] I understand that [if I ignore these instructions, my issue may be closed without review](https://github.com/caskroom/homebrew-cask/blob/master/doc/faq/closing_issues_without_review.md).

#### Description of issue

current cask downloads `MasterCollection_CS6_LS4.dmg`, which does not include English language, so it will install failed with error code -9.
Install image with English language is `MasterCollection_CS6_LS16.dmg`.
I suspect other cs6 cask have same problem.

#### Output of your command with `--verbose --debug`

```
==> Hbc::Installer#install
==> Printing caveats
==> Caveats
Installation or Uninstallation may fail with Exit Code 19 (Conflicting Processes running) if Browsers, Safari Notification Service or SIMBL Services (e.g. Flashlight) are running or Adobe Creative Cloud or any other Adobe Products are already installed. See Logs in /Library/Logs/Adobe/Installers if Installation or Uninstallation fails, to identifify the conflicting processes.

==> Hbc::Installer#fetch
==> Satisfying dependencies
==> Downloading
==> Downloading http://trials2.adobe.com/AdobeProducts/STAM/CS6/osx10/MasterCollection_CS6_LS4.dmg
Already downloaded: /Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg
==> Downloaded to -> /Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg
==> Verifying download
==> Determining which verifications to run for Cask adobe-cs6-master-collection
==> Checking for verification class Hbc::Verify::Checksum
==> 1 verifications defined
Hbc::Verify::Checksum
==> Running verification of class Hbc::Verify::Checksum
==> Verifying checksum for Cask adobe-cs6-master-collection
==> SHA256 checksums match
==> Installing Cask adobe-cs6-master-collection
==> Hbc::Installer#stage
==> Extracting primary container
==> Determining which containers to use based on filetype
==> Checking container class Hbc::Container::Pkg
==> Checking container class Hbc::Container::Ttf
==> Checking container class Hbc::Container::Otf
==> Checking container class Hbc::Container::Air
==> Checking container class Hbc::Container::Cab
==> Checking container class Hbc::Container::Dmg
==> Executing: ["/usr/bin/hdiutil", "imageinfo", "/Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg"]
==> Using container class Hbc::Container::Dmg for /Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s", "/Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg"]
==> Executing: ["/usr/bin/hdiutil", "convert", "-quiet", "-format", "UDTO", "-o", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s/adobe-cs6-master-collection--CS6.cdr", "/Users/teslamint/Library/Caches/Homebrew/Cask/adobe-cs6-master-collection--CS6.dmg"]
==> Executing: ["/usr/bin/hdiutil", "attach", "-plist", "-nobrowse", "-readonly", "-noidme", "-mountrandom", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s/adobe-cs6-master-collection--CS6.cdr"]
==> Executing: ["/usr/bin/find", ".", "-print0"]
==> Executing: ["/usr/bin/mkbom", "-s", "-i", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/20180210-6140-1yrusal.list", "--", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/20180210-6140-s5kt0x.bom"]
==> Executing: ["/usr/bin/ditto", "--bom", "/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/20180210-6140-s5kt0x.bom", "--", "/private/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s/dmg.kvIOkU", "/usr/local/Caskroom/adobe-cs6-master-collection/CS6"]
==> Executing: ["/usr/sbin/diskutil", "eject", "/private/var/folders/68/s6m_9t2x4dv2qxy2gbmv4ctr0000gn/T/d20180210-6140-alpc0s/dmg.kvIOkU"]
==> Creating metadata directory /usr/local/Caskroom/adobe-cs6-master-collection/.metadata/CS6/20180210144932.665.
==> Creating metadata subdirectory /usr/local/Caskroom/adobe-cs6-master-collection/.metadata/CS6/20180210144932.665/Casks.
==> Installing artifacts
==> 2 artifact/s defined
#<SortedSet:0x000001022f0de8>
==> Installing artifact of class Hbc::Artifact::PreflightBlock
==> Executing: ["/bin/launchctl", "list"]
==> Executing: ["/usr/bin/sudo", "-E", "--", "/usr/local/Caskroom/adobe-cs6-master-collection/CS6/Adobe CS6 Master Collection/Install.app/Contents/MacOS/Install", "--mode=silent", "--deploymentFile=/usr/local/Caskroom/adobe-cs6-master-collection/CS6/Adobe CS6 Master Collection/deploy/install-en_US.xml"]
Enter PIN for 'Certificate For PIV Authentication (Yubico PIV Authentication)':
==> Starting Installer...
==> File does not exist.
==> Exiting Installer with Code: -9
==> Purging files for version CS6 of Cask adobe-cs6-master-collection
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- /usr/local/Caskroom/adobe-cs6-master-collection/CS6/Adobe CS6 Master Collection/Install.app/Contents/MacOS/Install --mode=silent --deploymentFile=/usr/local/Caskroom/adobe-cs6-master-collection/CS6/Adobe CS6 Master Collection/deploy/install-en_US.xml

==> Standard Output of failed command:


==> Standard Error of failed command:
Starting Installer...
File does not exist.
Exiting Installer with Code: -9


==> Exit status of failed command:
#<Process::Status: pid 7782 exit 247>

/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:70:in `assert_success'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:36:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/system_command.rb:18:in `run!'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/dsl/base.rb:14:in `system_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cask_loader.rb:62:in `block (2 levels) in load'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `instance_eval'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:38:in `abstract_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/artifact/abstract_flight_block.rb:22:in `install_phase'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:174:in `block in install_artifacts'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/set.rb:674:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:166:in `install_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/installer.rb:80:in `install'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:20:in `block in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/install.rb:14:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli/abstract_command.rb:35:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:98:in `run_command'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:168:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
Error: Kernel.exit
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `exit'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:173:in `rescue in run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:156:in `run'
/usr/local/Homebrew/Library/Homebrew/cask/lib/hbc/cli.rb:132:in `run'
/usr/local/Homebrew/Library/Homebrew/cmd/cask.rb:8:in `cask'
/usr/local/Homebrew/Library/Homebrew/brew.rb:100:in `<main>'
```

#### Output of `brew cask doctor`

```
==> Homebrew-Cask Version
Homebrew-Cask 1.5.3-dirty
caskroom/homebrew-cask (git revision bb05a; last commit 2018-02-07)
==> macOS
10.13.4
==> SIP
Enabled
==> Java
1.8.0_162
==> Homebrew-Cask Install Location
<NONE>
==> Homebrew-Cask Staging Location
/usr/local/Caskroom
==> Homebrew-Cask Cached Downloads
~/Library/Caches/Homebrew/Cask (9 files, 8.7GB)
==> Homebrew-Cask Taps:
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask (3906 casks)
/usr/local/Homebrew/Library/Taps/teslamint/homebrew-caskroom (3 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-drivers (141 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-fonts (1159 casks)
/usr/local/Homebrew/Library/Taps/caskroom/homebrew-versions (177 casks)
/usr/local/Homebrew/Library/Taps/colindean/homebrew-fonts-nonfree (1 cask)
==> Contents of $LOAD_PATH
/usr/local/Homebrew/Library/Homebrew/cask/lib
/usr/local/Homebrew/Library/Homebrew
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/gems/2.3.0/gems/did_you_mean-1.0.0/lib
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/site_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby/2.3.0/universal-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/vendor_ruby
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/x86_64-darwin9.0
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/universal-darwin9.0
==> Environment Variables
LC_ALL="en_US.UTF-8"
PATH="/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Homebrew/Library/Homebrew/shims/scm"
SHELL="/bin/zsh"
```

**Comment by commitay** [comment]
cc @vitorgalvao @reitermarkus 

We might want to consider doing the same as we did with https://github.com/caskroom/homebrew-cask/issues/39224 and remove the `cs6` Casks.

**Comment by vitorgalvao** [comment]
[My position](https://github.com/caskroom/homebrew-cask/issues/39224#issuecomment-335312166) stands:

> There’s always *something* with Adobe. We’re not going to keep bending over backwards.

Agreed with removal.
